server {
    listen 80;
    index index.php index.html;
    root /var/www/src/public;

    # Optimize Nginx performance
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Browser caching cho tài nguyên tĩnh (Images, CSS, JS livewire/filament)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf|webp)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
    }
}